dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0        # لإرسال الطلبات للمواقع وجلب كود الـ HTML
  html: ^0.15.4        # لتفكيك كود الـ HTML واستخراج الروابط والبوسترات
  video_player: ^2.8.2 # المشغل الأساسي للفيديو من شركة جوجل
  chewie: ^1.8.1       # واجهة مشغل فيديو احترافية تحتوي على أزرار التحكم والتقديم
